# Generated by Django 4.2.8 on 2023-12-17 21:34

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0098_webhook_custom_field_data_webhook_tags'),
        ('ipam', '0067_ipaddress_index_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhcpLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('client_id', models.CharField(max_length=100)),
                ('lease_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
