# Generated by Django 4.2.8 on 2023-12-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0067_ipaddress_index_host'),
        ('netbox_dhcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcplease',
            name='hostname',
            field=models.CharField(default='noname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='mac_address',
            field=models.CharField(default='00-00-00-00-00-00', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='receiving_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='requested_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='ipam.ipaddress'),
        ),
    ]
