# Generated by Django 4.2.8 on 2023-12-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_dhcp', '0002_dhcplease_hostname_dhcplease_mac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcplease',
            name='local_context_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
