# Generated by Django 4.2.8 on 2024-01-02 20:17

from django.db import migrations, models
import django.db.models.deletion
import netbox_dhcp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0067_ipaddress_index_host'),
        ('netbox_dhcp', '0003_dhcplease_local_context_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcplease',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='client_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='expire_time',
            field=netbox_dhcp.models.DhcpLeaseExpireTime(blank=True),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='ip_address',
            field=netbox_dhcp.models.DhcpLeaseIPAddress(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='ipam.ipaddress', unique=True),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='lease_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='mac_address',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
