# Generated by Django 4.2.8 on 2024-01-12 19:16

from django.db import migrations
import django.db.models.deletion
import netbox_dhcp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0069_gfk_indexes'),
        ('netbox_dhcp', '0004_dhcplease_acknowledged_alter_dhcplease_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcplease',
            name='ip_address',
            field=netbox_dhcp.models.DhcpLeaseIPAddress(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='ipam.ipaddress'),
        ),
    ]
