# Generated by Django 5.1.5 on 2025-03-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_dhcp', '0005_alter_dhcplease_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcplease',
            name='client_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='mac_address',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]


