# Generated by Django 5.1.5 on 2025-03-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_dhcp', '0006_alter_dhcplease_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcplease',
            name='_config_context_data',
            field=models.JSONField(
                blank=True,
                null=True,
                editable=False,
            ),
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='_config_context_generation',
            field=models.PositiveBigIntegerField(
                default=0,
                editable=False,
            ),
        ),
    ]
