# Generated by Django 6.1 on 2026-09-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_dhcp', '0007_add_config_context_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhcplease',
            name='local_context_data',
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='client_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dhcplease',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
