FROM netboxcommunity/netbox:v4.7

RUN apt-get update && apt-get install -y git

COPY --chown=999:0 . /plugin_dhcp

RUN /usr/local/bin/uv pip install -r /plugin_dhcp/test/integration/plugin_requirements.txt
RUN sed -i '/.\/manage.py migrate --no-input/a  ./manage.py load_initializer_data --path /plugin_dhcp/test/integration/initializers' /opt/netbox/docker-entrypoint.sh
